%% SYNTAX TEST "source.mermaid" "git graph test"

gitGraph
%%%%%%%% <--- keyword.control.mermaid
  commit
  ^^^^^^  <--- keyword.control.mermaid
  commit id: "Normal"
  ^^^^^^  <--- keyword.control.mermaid
         ^^ <--- keyword.control.mermaid
           ^  <--- keyword.control.mermaid
             ^^^^^^^^ <--- string