%% SYNTAX TEST "source.mermaid" "graph flowchart test"

flowchart
%% <--------- keyword.control.mermaid 
  ID-1[Node 1]
%%^^^^ variable
%%    ^ keyword.control.mermaid 
%%     ^^^^^^ string
%%           ^ keyword.control.mermaid 