%% SYNTAX TEST "source.mermaid" "mindmap diagram test"

mindmap
%%<------- keyword.control.mermaid
  %% comment
%%^^^^^^^^^^ comment
  root
%%^^^^ string
  id[I am a square]
%%^^ variable
%%  ^ keyword.control.mermaid
%%   ^^^^^^^^^^^^^ string
%%                ^ keyword.control.mermaid
  id(I am a rounded square)
%%^^ variable
%%  ^ keyword.control.mermaid
%%   ^^^^^^^^^^^^^^^^^^^^^ string
%%                        ^ keyword.control.mermaid
  id((I am a circle))
%%^^ variable
%%  ^^ keyword.control.mermaid
%%    ^^^^^^^^^^^^^ string
%%                 ^^ keyword.control.mermaid
  id))I am a bang((
%%^^ variable
%%  ^^ keyword.control.mermaid
%%    ^^^^^^^^^^^ string
%%               ^^ keyword.control.mermaid
  id)I am a cloud(
%%^^ variable
%%  ^ keyword.control.mermaid
%%   ^^^^^^^^^^^^ string
%%               ^ keyword.control.mermaid
  id{{I am a hexagon}}
%%^^ variable
%%  ^^ keyword.control.mermaid
%%    ^^^^^^^^^^^^^^ string
%%                  ^^ keyword.control.mermaid
  ::icon(fa fa-book)
%%^^^^^^ keyword.control.mermaid
%%      ^ punctuation.parenthesis.open.mermaid
%%       ^^^^^^^^^^ string
%%                 ^ punctuation.parenthesis.close.mermaid
  :::urgent large
%%^^^ keyword.control.mermaid
%%   ^^^^^^^^^^^^ string
