%% SYNTAX TEST "source.mermaid" "quadrant chart test"

quadrantChart
%% <------------------ keyword.control.mermaid
    %% a comment
%%  ^^^^^^^^^^^^ comment
    title Reach and engagement of campaigns
%%  ^^^^^ keyword.control.mermaid
%%        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string
    x-axis Low Reach$&%/#.,?!*+='\-
%%  ^^^^^^ keyword.control.mermaid
%%         ^^^^^^^^^^^^^^^^^^^^^^^^ string
    x-axis Low Reach --> High Reach
%%  ^^^^^^ keyword.control.mermaid
%%         ^^^^^^^^^ string
%%                   ^^^ keyword.control.mermaid
%%                       ^^^^^^^^^^ string
    y-axis Low Engagement
%%  ^^^^^^ keyword.control.mermaid
%%         ^^^^^^^^^^^^^^ string
    y-axis Low Engagement --> High Engagement
%%  ^^^^^^ keyword.control.mermaid
%%         ^^^^^^^^^^^^^^ string
%%                        ^^^ keyword.control.mermaid
%%                            ^^^^^^^^^^^^^^^ string
    quadrant-1 We should expand
%%  ^^^^^^^^^^ keyword.control.mermaid
%%             ^^^^^^^^^^^^^^^^ string
    quadrant-2 Need to promote
%%  ^^^^^^^^^^ keyword.control.mermaid
%%             ^^^^^^^^^^^^^^^ string
    quadrant-3 Re-evaluate
%%  ^^^^^^^^^^ keyword.control.mermaid
%%             ^^^^^^^^^^^ string
    quadrant-4 May be improved
%%  ^^^^^^^^^^ keyword.control.mermaid
%%             ^^^^^^^^^^^^^^^ string
    Campaign A: [0.3, 0.6]
%%  ^^^^^^^^^^ string
%%            ^ keyword.control.mermaid
%%              ^ keyword.control.mermaid
%%               ^^^ constant.numeric.decimal.mermaid
%%                  ^ keyword.control.mermaid
%%                    ^^^ constant.numeric.decimal.mermaid
%%                       ^ keyword.control.mermaid
    Campaign B: [0.45, 0.23]
%%  ^^^^^^^^^^ string
%%            ^ keyword.control.mermaid
%%              ^ keyword.control.mermaid
%%               ^^^^ constant.numeric.decimal.mermaid
%%                   ^ keyword.control.mermaid
%%                     ^^^^ constant.numeric.decimal.mermaid
%%                         ^ keyword.control.mermaid