%% SYNTAX TEST "source.mermaid" "quadrant chart test"

quadrantChart
%% <------------------ keyword.control.mermaid
    %% a comment
%%  ^^^^^^^^^^^^ comment
    title Reach and engagement of campaigns
%%  ^^^^^ keyword.control.mermaid
%%        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string
    x-axis Low Reach$&%/#.,?!*+='\-
%%  ^^^^^^ keyword.control.mermaid
%%         ^^^^^^^^^^^^^^^^^^^^^^^^ string
    x-axis Low Reach --> High Reach
%%  ^^^^^^ keyword.control.mermaid
%%         ^^^^^^^^^ string
%%                   ^^^ keyword.control.mermaid
%%                       ^^^^^^^^^^ string
    y-axis Low Engagement
%%  ^^^^^^ keyword.control.mermaid
%%         ^^^^^^^^^^^^^^ string
    y-axis Low Engagement --> High Engagement
%%  ^^^^^^ keyword.control.mermaid
%%         ^^^^^^^^^^^^^^ string
%%                        ^^^ keyword.control.mermaid
%%                            ^^^^^^^^^^^^^^^ string
