%% SYNTAX TEST "source.mermaid" "requirement diagram test"

requirementDiagram
%% <------------------ keyword.control.mermaid
    %% a comment
%%  ^^^^^^^^^^^^ comment
    requirement test_req {
%%  ^^^^^^^^^^^ keyword.control.mermaid
%%              ^^^^^^^^ variable
%%                       ^ keyword.control.mermaid
    }
%%  ^ keyword.control.mermaid

    functionalRequirement test_req2 {
%%  ^^^^^^^^^^^^^^^^^^^^^ keyword.control.mermaid
%%                        ^^^^^^^^^ variable
%%                                  ^ keyword.control.mermaid
    }
%%  ^ keyword.control.mermaid

    performanceRequirement test_req3 {
%%  ^^^^^^^^^^^^^^^^^^^^^^ keyword.control.mermaid
%%                         ^^^^^^^^^ variable
%%                                   ^ keyword.control.mermaid
    }
%%  ^ keyword.control.mermaid

    interfaceRequirement test_req4 {
%%  ^^^^^^^^^^^^^^^^^^^^ keyword.control.mermaid
%%                       ^^^^^^^^^ variable
%%                                 ^ keyword.control.mermaid
    }
%%  ^ keyword.control.mermaid

    physicalRequirement test_req5 {
%%  ^^^^^^^^^^^^^^^^^^^ keyword.control.mermaid
%%                      ^^^^^^^^^ variable
%%                                ^ keyword.control.mermaid
    }
%%  ^ keyword.control.mermaid

    designConstraint test_req6 {
%%  ^^^^^^^^^^^^^^^^ keyword.control.mermaid
%%                   ^^^^^^^^^ variable
%%                             ^ keyword.control.mermaid
    }
%%  ^ keyword.control.mermaid
