%% SYNTAX TEST "source.mermaid" "state diagram v2 test"

stateDiagram-v2
%% <--------------- keyword.control.mermaid
  s1
%%^^ variable
  s1 --> s2
%%^^ variable
%%   ^^^ keyword.control.mermaid
%%       ^^ variable