%% SYNTAX TEST "source.mermaid" "user journey test"

journey
%%%%%%% <--- keyword.control.mermaid
  title My working day
%%^^^^^ keyword.control.mermaid
%%      ^^^^^^^^^^^^^^ string
  section Go to work
%%^^^^^^^ keyword.control.mermaid
%%        ^^^^^^^^^^ string
