%% SYNTAX TEST "source.mermaid" "user journey test"

journey
%%%%%%% <--- keyword.control.mermaid
  title My working day
%%^^^^^ keyword.control.mermaid
%%      ^^^^^^^^^^^^^^ string
  section Go to work
%%^^^^^^^ keyword.control.mermaid
%%        ^^^^^^^^^^ string
    Make tea: 5: Me
%%  ^^^^^^^^ string
%%          ^ keyword.control.mermaid
%%            ^ constant.numeric.decimal.mermaid
%%             ^ keyword.control.mermaid
%%               ^^ variable
    Do work: 1: Me, My Cat~=*%[]`&^$!"()
%%  ^^^^^^^ string
%%         ^ keyword.control.mermaid
%%           ^ constant.numeric.decimal.mermaid
%%            ^ keyword.control.mermaid
%%              ^^ variable
%%                ^ source.mermaid
%%                  ^^^^^^^^^^^^^^^^^^ variable

  %% negative cases
  invalid title text
%%^^^^^^^^^^^^^^^^^^ source.mermaid - keyword.control.mermaid
  invalid section text
%%^^^^^^^^^^^^^^^^^^^^ source.mermaid - keyword.control.mermaid
